APP_NAME = "Job Listing Scraper"
APP_VERSION = "1.0.0"

WINDOW_TITLE = f"{APP_NAME} v{APP_VERSION}"

WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 800

MIN_WIDTH = 1100
MIN_HEIGHT = 650

FONT_FAMILY = "Segoe UI"

TITLE_FONT = (FONT_FAMILY, 18, "bold")
HEADING_FONT = (FONT_FAMILY, 13, "bold")
TEXT_FONT = (FONT_FAMILY, 10)
BUTTON_FONT = (FONT_FAMILY, 10, "bold")

BUTTON_WIDTH = 20
PAD_X = 5

REQUEST_TIMEOUT = 15

MAX_JOBS = 100

DEFAULT_URL = "https://remoteok.com/"

CSV_EXTENSION = ".csv"
JSON_EXTENSION = ".json"

PROGRESS_MIN = 0
PROGRESS_MAX = 100