from pathlib import Path

APP_NAME = "Bulk File Renamer"
APP_VERSION = "1.0.0"

WINDOW_WIDTH = 1300
WINDOW_HEIGHT = 750

MIN_WIDTH = 1100
MIN_HEIGHT = 650

WINDOW_TITLE = f"{APP_NAME} v{APP_VERSION}"

FONT_FAMILY = "Segoe UI"

TITLE_FONT = (FONT_FAMILY, 18, "bold")
HEADING_FONT = (FONT_FAMILY, 13, "bold")
TEXT_FONT = (FONT_FAMILY, 11)
BUTTON_FONT = (FONT_FAMILY, 10, "bold")
STATUS_FONT = (FONT_FAMILY, 10)

PAD_X = 10
PAD_Y = 10

BUTTON_WIDTH = 18

DEFAULT_DIRECTORY = Path.home()

SUPPORTED_FILES = [
    ("All Files", "*.*"),
]

FULLSCREEN = False
RESIZABLE = True

PROGRESS_MIN = 0
PROGRESS_MAX = 100