from pathlib import Path

APP_NAME = "Email Automation"
APP_VERSION = "1.0.0"

WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 800

MIN_WIDTH = 1200
MIN_HEIGHT = 700

WINDOW_TITLE = f"{APP_NAME} v{APP_VERSION}"

FONT_FAMILY = "Segoe UI"

TITLE_FONT = (FONT_FAMILY, 18, "bold")
HEADING_FONT = (FONT_FAMILY, 13, "bold")
TEXT_FONT = (FONT_FAMILY, 11)
BUTTON_FONT = (FONT_FAMILY, 10, "bold")
STATUS_FONT = (FONT_FAMILY, 10)

PAD_X = 10
PAD_Y = 10

BUTTON_WIDTH = 18

DEFAULT_DIRECTORY = Path.home()

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

FULLSCREEN = False
RESIZABLE = True

PROGRESS_MIN = 0
PROGRESS_MAX = 100
